<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Starboard.Windows\Starboard.Windows.csproj" />
    <ProjectReference Include="..\Starboard.ConPtyTestHost\Starboard.ConPtyTestHost.csproj" />
    <ProjectReference Include="..\..\src\Modules\Starboard.Modules.Terminal\Starboard.Modules.Terminal.csproj" />
    <ProjectReference Include="..\..\src\Modules\Starboard.Modules.DesktopIntegration\Starboard.Modules.DesktopIntegration.csproj" />
    <ProjectReference Include="..\..\src\Modules\Starboard.Modules.Preferences\Starboard.Modules.Preferences.csproj" />
  </ItemGroup>
</Project>
